build: Update gettext-sys version in dist-vendor
gettext-sys got updated and the tarball name has changed. Now the 48.0
gnome-tour tarball fails with:

        error: failed to calculate checksum of: /home/buildozer/git/aports/community/gnome-tour/src/gnome-tour-48.0/vendor/gettext-sys/gettext-0.22.5.tar.xz

        Caused by:
          failed to open file `/home/buildozer/git/aports/community/gnome-tour/src/gnome-tour-48.0/vendor/gettext-sys/gettext-0.22.5.tar.xz`

Fixes: b37ae71b5738 ("Update dependencies")